CREATE TABLE endereco (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	pessoa_id BIGINT(20), 
	logradouro VARCHAR(50) NOT NULL,
	numero VARCHAR(10),
	complemento VARCHAR(15),
	bairro VARCHAR(40) NOT NULL,
	cep VARCHAR(9) NOT NULL,
	cidade VARCHAR(40) NOT NULL,
	estado VARCHAR(2) NOT NULL,
	flag_ende_princ VARCHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE endereco ADD CONSTRAINT fk_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (codigo);

DELETE FROM pessoa;

ALTER TABLE pessoa ADD cpf VARCHAR(14) NOT NULL;
ALTER TABLE pessoa ADD rg VARCHAR(15) NOT NULL;
ALTER TABLE pessoa ADD data_nasci DATE NOT NULL;


ALTER TABLE pessoa DROP COLUMN ativo;
ALTER TABLE pessoa DROP COLUMN logradouro;
ALTER TABLE pessoa DROP COLUMN numero;
ALTER TABLE pessoa DROP COLUMN complemento;
ALTER TABLE pessoa DROP COLUMN bairro;
ALTER TABLE pessoa DROP COLUMN cep;
ALTER TABLE pessoa DROP COLUMN cidade;
ALTER TABLE pessoa DROP COLUMN estado;



