CREATE TABLE TB_LANCAMENTO(
	ID BIGINT(50) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_VENCI DATE NOT NULL,
	DATA_PAGTO DATE,
	VALOR DECIMAL(10,2) NOT NULL,
	OBSERVACAO VARCHAR(200),
	TIPO VARCHAR(20) NOT NULL,
	ID_CATEGORIA BIGINT(50) NOT NULL,
	ID_PESSOA BIGINT(50) NOT NULL,
	FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria(codigo),
	FOREIGN KEY (ID_PESSOA) REFERENCES pessoa(codigo)	
) ENGINE =innoDB DEFAULT CHARSET=UTF8;

INSERT INTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES
			('',