CREATE TABLE TB_LANCAMENTO(
	ID BIGINT(50) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_VENCI DATE NOT NULL,
	DATA_PAGTO DATE,
	VALOR DECIMAL(10,2) NOT NULL,
	OBSERVACAO VARCHAR(200),
	TIPO VARCHAR(20) NOT NULL,
	ID_CATEGORIA BIGINT(50) NOT NULL,
	ID_PESSOA BIGINT(50) NOT NULL,
	FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria(codigo),
	FOREIGN KEY (ID_PESSOA) REFERENCES pessoa(codigo)	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Salário mensal','2017-06-10',null,6500.00,'Descrição de lucros','RECEITA',1,12);
INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Café','2017-06-12',null,6500.00, 'Descrição de lucros','RECEITA',1,12);
INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Bolinho de chuva','2017-06-15',null,5500.00, 'Descrição de lucros','DESPESA',1,13);
INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Pnus','2017-06-19',null,4500.00, 'Descrição de lucros','RECEITA',2,14);
INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Churrasco','2017-06-14',null,3500.00, 'Descrição de lucros','DESPESA',3,15);
INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Lanche','2017-06-18',null,2500.00, 'Descrição de lucros','DESPESA',4,16);
INSERT INTO TB_LANCAMENTO (DESCRICAO, DATA_VENCI, DATA_PAGTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Doces','2017-06-17',null,1500.00, 'Descrição de lucros','RECEITA',5,17);

